### ISSUE TITLE
Vosk models for Ukrainian

### ISSUE THREAD

**Issue by alumae** [Helsinki-NLP/UkrainianLT#1]
Vosk, an open-source realtime ASR system based on Kaldi, has Ukrainian models available:
https://alphacephei.com/vosk/models

**Comment by alumae** [comment]
Actually, this repo contains more links to ASR, TTS and speech resources for Ukrainian:
https://github.com/egorsmkv/speech-recognition-uk

**Comment by jorgtied** [comment]
Thanks - links added!
